title = "Pathfinder Character Template"

[owner]
name = "Spencer Mycek"
email = "Spence.Mycek@gmail.com"

[meta]
    name = ""
    player = "Spencer Mycek (GM)"
    class = [["Staff Magus", "16"], ["Mythic", "1"]]
    homeland = ""
    race = "Vanara"
    type = ["Humanoid (Vanara)"]
    gender = "M"
    age ="32"
    height = "6ft2in"
    weight = "190bs"
    hair = "brown"
    eyes = "green"

[stats]
    [stats.ability]
        # Score, Bonus, Temp Increase, Total Bonus
        str = [18, 4, 6, 7]
        dex = [18, 4, 6, 7]
        con = [14, 2, 6, 5]
        int = [20, 5, 6, 8]
        wis = [10, 0, 6, 3]
        cha = [7, -2, 6, 3]

    [stats.saves]
        # Total, Base, Score, Magic, Misc
        fort = [20, 10, 5, 5, 0]
        refl = [17, 5, 7, 5, 0]
        will = [18, 10, 3, 5, 0]

    [stats.speed]
        land = 30
        fly = 0
        swim = 0
        climb = 0
        burrow = 0

    [stats.skills]
        rpl = 0
        ranks = 0
        # Name, ranks 
        skills = [""]
    [stats.skills.languages]
        languages = [""]
    [stats.prof]
        proficienies = [""]

    [stats.combat]
        hp = 0
        init = 0
        bab = 0
        cmb = 0
        cmd = 0
        sr = ""

    [stats.combat.ac]
        ac = 10
        touch = 10
        flat = 10

    [stats.weapons]
        [stats.weapons.1]
            name = ""
            damage = ""
            range = ""
            crit = ["20", "2x"]
            type = [""]

[inventory]
    items = [""]

    [inventory.wealth]
        gp=0
        sp=0

    [inventory.carry]
        heavy=100
        medium=66
        light=33

[spells]
    known = 0
    level = 0
    slots = 0
    spells = [""]

[feats]
    1=""
    2=""
    
    [feats.traits]
    social=""
    combat=""
    magic=""

    [feats.drawbacks]
    major=""
    1=""
    2=""

[abilities]
    abilities=[""]
    
    [abilities.class]
    class=[""]


